import 'dart:typed_data';

import '../../core/enums/precise_ref_type.dart';
import '../../data/models/character/character_prompt.dart' as ui_character;
import '../../data/models/image/image_params.dart';
import '../../data/models/recipe/prompt_recipe.dart';
import '../../data/models/vibe/vibe_reference.dart';

/// Transient, user-selected bytes used to reattach a binary-free recipe.
///
/// These values are deliberately not persisted. Keys for Vibe and Precise
/// references are the snapshot ids; Precise snapshots without an id use the
/// deterministic `precise-{index}` fallback generated by the recipe schema.
class PromptRecipeAttachments {
  PromptRecipeAttachments({
    this.sourceImage,
    Map<String, VibeReference> vibeReferences = const {},
    Map<String, Uint8List> preciseReferences = const {},
  }) : vibeReferences = Map.unmodifiable(vibeReferences),
       preciseReferences = Map.unmodifiable(preciseReferences);

  const PromptRecipeAttachments.empty()
    : sourceImage = null,
      vibeReferences = const {},
      preciseReferences = const {};

  final Uint8List? sourceImage;
  final Map<String, VibeReference> vibeReferences;
  final Map<String, Uint8List> preciseReferences;

  bool get isEmpty =>
      sourceImage == null &&
      vibeReferences.isEmpty &&
      preciseReferences.isEmpty;
}

/// Result of restoring a binary-free recipe into editor state.
///
/// References whose bytes are intentionally absent from a recipe are reported
/// separately so the UI can ask the user to reattach them instead of sending
/// an invalid request.
class PromptRecipeRestorationResult {
  const PromptRecipeRestorationResult({
    required this.params,
    required this.characters,
    required this.globalAiChoice,
    required this.hasUnavailableImageInput,
    required this.unavailableVibeCount,
    required this.unavailablePreciseReferenceCount,
    this.reattachedImageInput = false,
    this.reattachedVibeCount = 0,
    this.reattachedPreciseReferenceCount = 0,
  });

  final ImageParams params;
  final List<ui_character.CharacterPrompt> characters;
  final bool globalAiChoice;
  final bool hasUnavailableImageInput;
  final int unavailableVibeCount;
  final int unavailablePreciseReferenceCount;

  /// Number of references explicitly supplied by the user for this restore.
  final bool reattachedImageInput;
  final int reattachedVibeCount;
  final int reattachedPreciseReferenceCount;

  bool get hasUnavailableReferences =>
      hasUnavailableImageInput ||
      unavailableVibeCount > 0 ||
      unavailablePreciseReferenceCount > 0;
}

/// Converts a persisted recipe into safe, editor-ready state.
///
/// Recipe records never contain image bytes. Any generation mode that needs a
/// source image is therefore restored as plain text generation until the user
/// supplies a new source. Vibe and Precise Reference entries are likewise
/// cleared while their missing counts remain available to the caller.
class PromptRecipeRestorationService {
  const PromptRecipeRestorationService._();

  static PromptRecipeRestorationResult restore(
    PromptRecipe recipe, {
    PromptRecipeAttachments attachments = const PromptRecipeAttachments.empty(),
  }) {
    final snapshot = recipe.request;
    final requiresSourceImage = snapshot.imageToImage != null;
    final sourceImage = _validBytes(attachments.sourceImage);
    final hasCharacters = recipe.characters.isNotEmpty;
    final useCoordinates = hasCharacters && snapshot.params.useCoords;
    final restoredCharacters = [
      for (final character in recipe.characters)
        _restoreCharacter(character, useCoordinates: useCoordinates),
    ];

    final attachedVibes = <VibeReference>[];
    for (var index = 0; index < snapshot.vibeTransfers.length; index++) {
      final transfer = snapshot.vibeTransfers[index];
      final key = transfer.id.isEmpty ? 'vibe-$index' : transfer.id;
      final selected = attachments.vibeReferences[key];
      if (selected == null) continue;
      if (!selected.hasVibeEncoding && !selected.canReencodeFromRawSource) {
        continue;
      }
      attachedVibes.add(
        selected.copyWith(
          displayName: transfer.filename,
          thumbnail: _validBytes(selected.thumbnail),
          rawImageData: _validBytes(selected.rawImageData),
          strength: VibeReference.sanitizeStrength(transfer.strength),
          infoExtracted: VibeReference.sanitizeInfoExtracted(
            transfer.informationExtracted,
          ),
          enabled: true,
        ),
      );
    }

    final attachedPrecise = <PreciseReference>[];
    for (var index = 0; index < snapshot.preciseReferences.length; index++) {
      final reference = snapshot.preciseReferences[index];
      final key = reference.id ?? 'precise-$index';
      final selected = _validBytes(attachments.preciseReferences[key]);
      if (selected == null) continue;
      attachedPrecise.add(
        PreciseReference(
          image: selected,
          type: _preciseType(reference.type),
          strength: reference.strength,
          fidelity: reference.fidelity,
          enabled: true,
        ),
      );
    }

    final restoredParams = snapshot.params.copyWith(
      sourceImage: sourceImage,
      maskImage: null,
      vibeReferencesV4: attachedVibes,
      preciseReferences: attachedPrecise,
      characters: const [],
      // A source-less transformation cannot be sent safely. Once the user
      // explicitly supplies a source, restore it as ordinary img2img; masks
      // are never guessed or revived from a binary-free recipe.
      action: sourceImage == null
          ? ImageGenerationAction.generate
          : ImageGenerationAction.img2img,
      strength: sourceImage == null
          ? snapshot.params.strength
          : (snapshot.imageToImage?.strength ?? snapshot.params.strength),
      noise: sourceImage == null
          ? snapshot.params.noise
          : (snapshot.imageToImage?.noise ?? snapshot.params.noise),
      isOutpaint: false,
      isEnhanceRequest: false,
      inpaintMaskClosingIterations: 0,
      inpaintMaskExpansionIterations: 0,
    );

    return PromptRecipeRestorationResult(
      params: restoredParams,
      characters: List.unmodifiable(restoredCharacters),
      globalAiChoice: !useCoordinates,
      hasUnavailableImageInput: requiresSourceImage && sourceImage == null,
      unavailableVibeCount:
          snapshot.vibeTransfers.length - attachedVibes.length,
      unavailablePreciseReferenceCount:
          snapshot.preciseReferences.length - attachedPrecise.length,
      reattachedImageInput: sourceImage != null,
      reattachedVibeCount: attachedVibes.length,
      reattachedPreciseReferenceCount: attachedPrecise.length,
    );
  }

  static Uint8List? _validBytes(Uint8List? bytes) {
    if (bytes == null || bytes.isEmpty) return null;
    return Uint8List.fromList(bytes);
  }

  static PreciseRefType _preciseType(String value) {
    for (final type in PreciseRefType.values) {
      if (type.name == value || type.toApiString() == value) return type;
    }
    return PreciseRefType.characterAndStyle;
  }

  static ui_character.CharacterPrompt _restoreCharacter(
    RecipeCharacter character, {
    required bool useCoordinates,
  }) {
    final customPosition = useCoordinates
        ? ui_character.CharacterPosition(
            mode: ui_character.CharacterPositionMode.custom,
            row: character.center.y.clamp(0.0, 1.0).toDouble(),
            column: character.center.x.clamp(0.0, 1.0).toDouble(),
          )
        : null;
    return ui_character.CharacterPrompt(
      id: character.id,
      name: character.name,
      gender: _restoreGender(character.gender, character.prompt),
      prompt: character.prompt,
      negativePrompt: character.negativePrompt,
      positionMode: useCoordinates
          ? ui_character.CharacterPositionMode.custom
          : ui_character.CharacterPositionMode.aiChoice,
      customPosition: customPosition,
      enabled: character.enabled,
    );
  }

  static ui_character.CharacterGender _restoreGender(
    String? value,
    String prompt,
  ) {
    switch (value?.toLowerCase()) {
      case 'female':
        return ui_character.CharacterGender.female;
      case 'male':
        return ui_character.CharacterGender.male;
      case 'other':
        return ui_character.CharacterGender.other;
    }
    final lowerPrompt = prompt.toLowerCase();
    if (lowerPrompt.contains('1girl') || lowerPrompt.contains('girl')) {
      return ui_character.CharacterGender.female;
    }
    if (lowerPrompt.contains('1boy') || lowerPrompt.contains('boy')) {
      return ui_character.CharacterGender.male;
    }
    return ui_character.CharacterGender.other;
  }
}
